version: "3.3"

services:
  gitlab:
    restart: always
    network_mode: host
    image: gitlab/gitlab-ce:latest
    ports:
      - "22"
      - "80"
      - "443"
    volumes:
      - "data:/var/opt/gitlab"
      - "logs:/var/log/gitlab"
      - "config:/etc/gitlab"
      - ./gitlab.rb:/omnibus_config.rb
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    secrets:
      - gitlab_root_password

  gitlab-runner:
    restart: always
    network_mode: host
    image: gitlab/gitlab-runner:alpine
    volumes:
      - "./runner:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
      
  # git lab has its own registry per project, no need for your own docker image registry
  # registry:
  #   network_mode: host
  #   restart: always
  #   image: registry:2
  #   ports:
  #     - "4567"
  #   volumes:
  #     - "./registry:/var/lib/registry"
  #   environment:
  #     REGISTRY_HTTP_ADDR: "0.0.0.0:4567"

secrets:
  gitlab_root_password:
    file: ./root_password.txt

volumes:
  data:
  logs:
  config:
